# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-07-24 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('institution_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Institution Type')),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Institution Name')),
                ('petitioner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Petitioner Name')),
                ('counter_filed', models.BooleanField(default=False)),
                ('date_of_order', models.DateTimeField()),
            ],
            options={
                'db_table': 'records',
            },
        ),
    ]
