# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-07-25 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrecords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('case_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Case Type')),
            ],
            options={
                'db_table': 'case_type',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('dist_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='InstitutionName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('institution_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Institution Name')),
            ],
            options={
                'db_table': 'institution_name',
            },
        ),
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('institution_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Institution Type')),
            ],
            options={
                'db_table': 'institution_type',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('state_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.AddField(
            model_name='institutionname',
            name='institution_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrecords.InstitutionType'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrecords.State'),
        ),
    ]
