# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-07-29 20:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecords', '0002_auto_20190726_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='case_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Case Number'),
        ),
        migrations.AddField(
            model_name='records',
            name='case_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Case Type'),
        ),
        migrations.AddField(
            model_name='records',
            name='cf_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='records',
            name='cf_lr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CF letter no'),
        ),
        migrations.AddField(
            model_name='records',
            name='dist',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='records',
            name='fao_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='records',
            name='fao_filed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='records',
            name='fao_lr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FAO letter no'),
        ),
        migrations.AddField(
            model_name='records',
            name='file_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File Number'),
        ),
        migrations.AddField(
            model_name='records',
            name='memorandum_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='records',
            name='memorandum_sought',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='records',
            name='mr_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='records',
            name='mr_lr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Memorandum Reveived letter no'),
        ),
        migrations.AddField(
            model_name='records',
            name='ms_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='records',
            name='ms_lr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Memorandum sought letter no'),
        ),
        migrations.AddField(
            model_name='records',
            name='sc_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='records',
            name='sc_lr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status of comp letter no'),
        ),
        migrations.AddField(
            model_name='records',
            name='status_of_comp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status of compliance'),
        ),
        migrations.AlterField(
            model_name='records',
            name='date_of_order',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
