# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-07-29 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecords', '0003_auto_20190730_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='cf_dt',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='date_of_order',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='dist',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='records',
            name='fao_dt',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='mr_dt',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='ms_dt',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='sc_dt',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
