# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-07-30 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecords', '0004_auto_20190730_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='record_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Record Name'),
        ),
    ]
